I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 127, in script
    $ say_with_voice("incorrect.mp3", "hiii guys", f)
  File "game/script.rpy", line 127, in <module>
    $ say_with_voice("incorrect.mp3", "hiii guys", f)
  File "game/script.rpy", line 5, in say_with_voice
    renpy.music.wait_stop(channel='voice')
AttributeError: module 'renpy.audio.music' has no attribute 'wait_stop'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 127, in script
    $ say_with_voice("incorrect.mp3", "hiii guys", f)
  File "/home/jrcarguy11/renpy-8.3.7-sdk/renpy/ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/jrcarguy11/renpy-8.3.7-sdk/renpy/python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 127, in <module>
    $ say_with_voice("incorrect.mp3", "hiii guys", f)
  File "game/script.rpy", line 5, in say_with_voice
    renpy.music.wait_stop(channel='voice')
AttributeError: module 'renpy.audio.music' has no attribute 'wait_stop'

Linux-6.6.66-06602-g2b73872e56ce-x86_64-with-glibc2.36 x86_64
Ren'Py 8.3.7.25031702
Echo Chaser 1.0
Fri Apr  4 14:35:00 2025
