I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 118, in script
    if running:
  File "game/script.rpy", line 118, in <module>
    if running:
NameError: name 'running' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 118, in script
    if running:
  File "/home/birb/Downloads/renpy-8.3.7-sdk/renpy/ast.py", line 1856, in execute
    if renpy.python.py_eval(condition):
  File "/home/birb/Downloads/renpy-8.3.7-sdk/renpy/python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/home/birb/Downloads/renpy-8.3.7-sdk/renpy/python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 118, in <module>
    if running:
NameError: name 'running' is not defined

Linux-6.8.0-51-generic-x86_64-with-glibc2.39 x86_64
Ren'Py 8.3.7.25031702
Echo Chaser 1.0
Sun Apr  6 15:25:22 2025
